version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/proxy.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      external_network:

  acme-companion:
    image: nginxproxy/acme-companion
    restart: always
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      external_network:
volumes:
  certs:
  conf.d:
  vhost.d:
  html:
  proxy.conf:
  acme.sh:
networks:
  external_network:
      name: my-nginx-proxy
      external: true
